services:
  pgdb:
    image: postgres:latest
    container_name: pg-database
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pgadmin-user -d dockerdatabase" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_django
    ports:
      - "8888:80"
    env_file:
      - .env
    depends_on:
      - pgdb
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dj_rabbit
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "4369:4369"
      - "5671:5671"
      - "15672:15672"
    depends_on:
      - pgdb

  redis:
    image: redis:latest
    container_name: dj-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis:/var/lib/redis/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  local_pgdata:
  pgadmin-data:
  redis:
