# Generated by Django 5.1.2 on 2024-10-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_videofile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=100),
        ),
    ]
