# Generated by Django 5.1.2 on 2024-10-26 20:06

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_alter_videofile_user_alter_dislike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(max_length=2000, upload_to=channel.models.video_upload_path),
        ),
    ]
