# Generated by Django 5.1.2 on 2024-11-01 18:29

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0011_alter_videofile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='hsl_file',
            field=models.FileField(blank=True, null=True, upload_to=channel.models.video_upload_path),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived'), ('Processing', 'Processing'), ('Ready to publish', 'Ready to publish')], db_index=True, default='Draft', max_length=100),
        ),
    ]
