# Generated by Django 5.1.2 on 2024-11-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_videofile_hsl_file_alter_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived'), ('Processing', 'Processing'), ('Process Completed', 'Process Completed')], db_index=True, default='Draft', max_length=100),
        ),
    ]
